[package]
name = "monotaur"
version = "0.1.0"
authors = ["porplax"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "*", features = ['derive']}
hashbrown = "0.12.3"
syscalls = "*"
